= Setup
include::_attributes.adoc[]

[#prerequisites]
== Prerequequisites

Ansible has multiples ways to be installed. This lesson explores this aspect.

[#installingcontrolnode]
== Installing Control Node

To install the Ansible Engine connect to the machine you want to use to execute ansible, the ansible controller from now on, and as root user:

[source,bash,subs="+macros,+attributes"]
[root@controller ~]# dnf install epel-release -y
...
[root@controller ~]# dnf install ansible git -y
...
[root@controller ~]#

As a best practice you should create a non-privileged user to execute ansible so:

[source,bash,subs="+macros,+attributes"]
[root@controller ~]# useradd -md /home/devops devops
[root@controller ~]# passwd devops
Changing password for user devops.
New password: 
BAD PASSWORD: The password is shorter than 8 characters
Retype new password: 
passwd: all authentication tokens updated successfully.
[root@controller ~]#

From now on we will use the **devops** user in the controller node to create and execute ansible tasks.

As ansible will use SSH to connect to Linux clients we need to create a SSH public/private key to connect to Linux clients where we want to perform tasks using ansible. As **devops** user:

[source,bash,subs="+macros,+attributes"]
[devops@controller ~]$ ssh-keygen -t rsa -b 4096
Generating public/private rsa key pair.
Enter file in which to save the key (/home/devops/.ssh/id_rsa): 
Created directory '/home/devops/.ssh'.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/devops/.ssh/id_rsa
Your public key has been saved in /home/devops/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:kuIq9VLRci2GwyJQrizANZiDsnmAwPxNEzrbCMlmhVE devops@controller
The key's randomart image is:
+---[RSA 4096]----+
|BoBE ..          |
|OO+ oo           |
|+@++oo..         |
|O.+.@.=..        |
|o+ +.Bo.S        |
|. .... .         |
| . o.            |
|. ...            |
| ...             |
+----[SHA256]-----+
[devops@controller ~]$

You can see a more detailed information in section <<usefullinks>>.

[#installingansibleclients]
== Installing Ansible Clients

We need at least one Linux client. We need to perform the following actions in the Linux client to be able to execute ansible tasks within.

Ansible needs an user to connect to the client to perform tasks so we will create a user which will be used for ansible to connect to the client:

[source,bash,subs="+macros,+attributes"]
[root@client ~]# useradd -md /home/ansible ansible
[root@client ~]#

As ansible will use public key authentication to connect we do not configure a password for the user. It is posible to use use password traditional authentication to connect to the Linux client when ansible connects but this authentication method is not used.

[#usefullinks]
== Useful Links

For more information, please visit:

* https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-the-control-node

[#authorinformation]
== Author Information

Asier Cidon - Cloud Consultant
asier.cidon@redhat.com