= Ansible AdHoc Commands
include::_attributes.adoc[]

[#introduction]
== Introduction

AdHoc command allows execute a single Ansible task in a programmatic and simple way.
This lesson dives in this Ansible feature.

An AdHoc command follow this structure:
[source,bash,subs="+macros,+attributes"]
$ ansible [pattern] --module-name [module] --args "[module options]"

Where the **pattern** is to indicate the target hosts and groups.
It can be a single host or a group of hosts. In this example we are going to use
only one host, the localhost.

Where **module** is the name of the module you want to execute. There are many modules in Ansible,
later we will see them in detail. For now, it is important to know that modules help us execute tasks on hosts.

An example of a module is "debug", this module is used to print statements at runtime
and can be useful for debugging variables or expressions. Let's run our first hello world in Ansible using debug!

[source,bash,subs="+macros,+attributes"]
$ ansible localhost --module-name debug --args 'msg="My first Hello world in Ansible!!"'

NOTE: you can abbreviate the commands, --module-name or simply -m  and for --args you can use -a

The above command can be run this way too:
[source,bash,subs="+macros,+attributes"]
$ ansible localhost -m debug -a 'msg="My first Hello world in Ansible!!"'

To find out more details about a module, you can use **ansible-doc**.
It is to consult the documentation but from the command line. Very useful!

Example:
[source,bash,subs="+macros,+attributes"]
$ ansible-doc debug


[#steps]
== Steps


[#usefullinks]
== Useful Links

For more information, please visit:

* https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#id3
* https://docs.ansible.com/ansible/latest/user_guide/modules.html#working-with-modules
* https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
