= Ansible AdHoc Commands
include::_attributes.adoc[]


[#introduction]
== Introduction

AdHoc command allows execute a single Ansible task in a programmatic and simple way.
This lesson dives in this Ansible feature.

An AdHoc command follow this structure:
[source,bash,subs="+macros,+attributes"]
$ ansible [pattern] --module-name [module] --args "[module options]"

Where the **pattern** is to indicate the target hosts and groups.
It can be a single host or a group of hosts. In this example we are going to use
only one host, the localhost.

Where **module** is the name of the module you want to execute. There are many modules in Ansible,
later we will see them in detail. For now, it is important to know that modules help us execute tasks on hosts.

An example of a module is "debug", this module is used to print statements at runtime
and can be useful for debugging variables or expressions. Let's run our first hello world in Ansible using debug!

[source,bash,subs="+macros,+attributes"]
$ ansible localhost --module-name debug --args 'msg="My first Hello world in Ansible!!"'

NOTE: you can abbreviate the commands, --module-name or simply -m  and for --args you can use -a

The above command can be run this way too:
[source,bash,subs="+macros,+attributes"]
$ ansible localhost -m debug -a 'msg="My first Hello world in Ansible!!"'

To find out more details about a module, you can use **ansible-doc**.
It is to consult the documentation but from the command line. Very useful!

Example:
[source,bash,subs="+macros,+attributes"]
$ ansible-doc debug


[#steps]
== Steps

In the next exercise we are going to create a new user using AdHoc command.

First, execute this instruction:
[source,bash,subs="+macros,+attributes"]
$ ansible localhost -c local -m user -a "name=yourname"

Did it show any error? Why?
Create a new user requires special permissions and we are going to identify
how to indicate these permissions in Ansible.

Let's try this:
[source,bash,subs="+macros,+attributes"]
$ ansible localhost -c local -m user -a "name=yourname" --become

Now that you know the parameter **--become**. It is important to know that when
you run commands at the command line, you can interact with the execution.
In this case, you must provide the password of the user "student" to be able to
execute commands with privileges:

[source,bash,subs="+macros,+attributes"]
$ ansible localhost -c local -m user -a "name=yourname" --become --ask-become-pass

How can I check that the user has been created?
with this command you can check the new user is created:
[source,bash,subs="+macros,+attributes"]
$ ls /home/


[#usefullinks]
== Useful Links

For more information, please visit:

* https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#id3
* https://docs.ansible.com/ansible/latest/user_guide/modules.html#working-with-modules
* https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
* https://docs.ansible.com/ansible/latest/user_guide/become.html
